### ISSUE TITLE
Build broken with "go_register_toolchains() got unexpected keyword argument: version (did you mean 'go_version'?)"

### ISSUE THREAD

**Issue by mithro** [google/verible#625]
```
+ bazel test -c opt --show_progress_rate_limit=10.0 //...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
DEBUG: Rule 'io_kythe' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "bee43a5908ce99cb9cf5a2cd42dc2da2972707f8", shallow_since = "1607448149 -0800" and dropping ["branch"]
DEBUG: Repository io_kythe instantiated at:
  /home/runner/work/verible/verible/WORKSPACE:143:15: in <toplevel>
Repository rule git_repository defined at:
  /home/runner/.cache/bazel/_bazel_runner/7495b8e990fa395aae00b9d0b9ec359d/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: Traceback (most recent call last):
	File "/home/runner/work/verible/verible/WORKSPACE", line 155, column 19, in <toplevel>
		kythe_dependencies()
	File "/home/runner/.cache/bazel/_bazel_runner/7495b8e990fa395aae00b9d0b9ec359d/external/io_kythe/external.bzl", line 1229, column 23, in kythe_dependencies
		_rule_dependencies()
	File "/home/runner/.cache/bazel/_bazel_runner/7495b8e990fa395aae00b9d0b9ec359d/external/io_kythe/external.bzl", line 30, column 27, in _rule_dependencies
		go_register_toolchains(version = "1.15.5")
	File "/home/runner/.cache/bazel/_bazel_runner/7495b8e990fa395aae00b9d0b9ec359d/external/io_bazel_rules_go/go/private/sdk.bzl", line 241, column 5, in go_register_toolchains
		def go_register_toolchains(go_version = None, nogo = None):
Error: go_register_toolchains() got unexpected keyword argument: version (did you mean 'go_version'?)
```

**Comment by fangism** [comment]
@ivan444 FYI.
For reference current top-of-tree of that file is
https://github.com/bazelbuild/rules_go/blob/master/go/private/sdk.bzl

and contains:

```starlark
def go_register_toolchains(version = None, nogo = None, go_version = None):
    """See /go/toolchains.rst#go-register-toolchains for full documentation."""
    if not version:
        version = go_version  # old name
```

There are some newer releases at https://github.com/bazelbuild/rules_go/releases, I'll try some of those in our WORKSPACE file.
